name: PROJETOS dos Exercícios 4º bimestre - 2º ANO

on:
  push:
  workflow_dispatch:

jobs:
  projeto5-servidor-http:
    name: projeto5-servidor-http
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/poo/projetos/projeto5-servidor-http
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto6-api-de-catalogo:
    name: projeto6-api-de-catalogo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/poo/projetos/projeto6-api-de-catalogo
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test