name: Exerc√≠cios

on:
  push:
  workflow_dispatch:

jobs:
  ex02-teste-de-multiplicacao:
    name: ex02-teste-de-multiplicacao
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/teste-de-software/ex02-teste-de-multiplicacao
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test